### ISSUE TITLE
Error/Warning about get_root_logger and load_checkpoint

### ISSUE THREAD

**Issue by mighty98** [plemeri/InSPyReNet#43]
@plemeri First of all thank you for the work. Its really awesome

I am trying to use this but i am getting these errors and I cannot figure out from where we are using these. Can you please help me out.. This is in the backbones/SwinTransformer file
![image](https://github.com/plemeri/InSPyReNet/assets/32213921/05ab2bb5-0764-4519-9ba4-f0da34e495f6)

**Comment by plemeri** [comment]
Hi @mighty98, the swin transformer backbone is brought from [Swin Github Repo](https://github.com/microsoft/Swin-Transformer). Please refer to the original repository.

If you are trying to run the inference code only to generate mask, then try disable pretrained option.
[pretrained option link](https://github.com/plemeri/InSPyReNet/blob/96037a04090fbc6125bc6a23adf44daba813b4dc/configs/InSPyReNet_SwinB.yaml#L4)
```
Model:
    name: "InSPyReNet_SwinB"
    depth: 64
    pretrained: True --> change this into False
    base_size: [384, 384]
    threshold: 512
```

Also, you can try using our python API & command line tool [`transparent-background`](https://github.com/plemeri/transparent-background) which is identical to this work but with more user friendly interface.

If you are trying to train on your own, then please feel free to add a comment for more help. I'll help you with this problem in that case.

Thanks.
